[build]
 command = 'npm run build'
 publish = '/dist'
 functions = '../comfy-server/netlify_functions'

[[redirects]]
 from = '/store/*'
 to = '/.netlify/functions/:splat'
 status = 200

[[redirects]]
from = '/*'
to = '/index.html'
status = 200
