[build]
 command = 'npm run build'
 publish = '/build'
 functions = './comfy-server'

[[redirects]]
 from = '/store/*'
 to = '/.netlify/functions/:splat'
 status = 200

[[redirects]]
from = '/*'
to = '/index.html'
status = 200
